version: "3.8"

services:
  # Backend service
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./backend/uploads:/app/uploads
    environment:
      - PORT=8000
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_DB_NAME=${MONGODB_DB_NAME:-resume_extractor}
      - CORS_ORIGINS=http://localhost:3000,http://localhost:80,http://localhost,http://frontend:80,http://frontend
    ports:
      - "8000:8000"
    networks:
      - app-network
    restart: unless-stopped

  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
